### ISSUE TITLE
Provide liftTyped

### ISSUE THREAD

**Issue by phadej** [haskell-compat/th-compat#10]
Which would return `Code` always. Older TH dont' even have `liftTyped` which makes need for compat even stronger.

**Comment by RyanGlScott** [comment]
Is [`liftTypedQuote`](https://hackage.haskell.org/package/th-compat-0.1.2/docs/Language-Haskell-TH-Syntax-Compat.html#v:liftTypedQuote) what you are looking for?

**Comment by phadej** [comment]
Thank you. There are so many `lift*` functions that I got confused.
