### ISSUE TITLE
Add makeRelativeToProject

### ISSUE THREAD

**Issue by phadej** [haskell-compat/th-compat#12]
It would be great to have it in `th-compat` as a "canonical" compat place. The implementation as in `file-embed` should be fine.

I'll make a PR if this addition is welcome.

see https://well-typed.com/blog/2022/01/multiple-home-units/

**Comment by RyanGlScott** [comment]
That sounds reasonable to me. Make sure to update the `.cabal` project and Haddocks to reflect the fact that we're now backporting more things besides `Code` and `Quote`. Thanks!

**Comment by phadej** [comment]
FYI: https://gitlab.haskell.org/ghc/ghc/-/issues/21738#note_437547

I'd delay the release of `th-compat` until that issue is figured out.

**Comment by RyanGlScott** [comment]
If I'm reading the discussion on https://gitlab.haskell.org/ghc/ghc/-/issues/21738 correctly, this issue has been resolved by https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8516. As a result, the API that we backported to `th-compat` in #14 is still valid. Is that correct? If so, I can cut a new release soon.

**Comment by phadej** [comment]
> As a result, the API that we backported to th-compat in 

I think so.

I haven't installed GHC-9.4.1-rc1 yet, but I'd expect API there to not change. OTOH, I can wait until proper 9.4.1 release as well.

**Comment by RyanGlScott** [comment]
Indeed, I don't expect that this API would change either. And I happen to be in the process of making some new Hackage releases anyway, so why not?

I've uploaded [`th-compat-0.1.4`](https://hackage.haskell.org/package/th-compat-0.1.4) to Hackage with these changes.
