### ISSUE TITLE
Release to Hackage

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-compat/th-compat#2]
There's [one more upstream GHC patch](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3800#note_291570) that I'd like to land and backport to `th-compat` before an initial Hackage release, but otherwise, I think this package is mostly ready to go.

**Comment by phadej** [comment]
Should that patch/issue have a milestone / tag to be backported to GHC-9.0?

**Comment by RyanGlScott** [comment]
Sure. I've added the corresponding 9.0.1 milestone and labels for [#18521](https://gitlab.haskell.org/ghc/ghc/-/issues/18521) and [!3800](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3800).

**Comment by RyanGlScott** [comment]
I've backported the fix for [GHC#18521](https://gitlab.haskell.org/ghc/ghc/-/issues/18521) in #3. Unless anyone else speaks up, I plan to upload `th-compat` to Hackage soon-ish (perhaps just before a GHC 9.0.1 alpha release).

**Comment by RyanGlScott** [comment]
One other possible function that might warrant inclusion in `th-compat` is something like this:

```hs
-- TODO: What is a good name for this function? Suggestions welcome.
#if MIN_VERSION_template_haskell(2,17,0)
liftTypedFromUntyped :: (Lift t, Quote m) => t -> Code m t
liftTypedFromUntyped = unsafeCodeCoerce . liftQuote
#elif MIN_VERSION_template_haskell(2,16,0)
liftTypedFromUntyped :: (Lift t, Quote m) => t -> m (TExp t)
liftTypedFromUntyped = unsafeTExpCoerce . liftQuote
#endif
```

This is a strange function, since its type differs depending on what version of `template-haskell` you are using. But I do have a pressing need for it, as I find myself re-defining this function in many different spots when writing patches to make libraries support `template-haskell-2.17.0.0`. In `head.hackage` alone, I have independently implemented this function in [`th-lift`](https://gitlab.haskell.org/ghc/head.hackage/-/blob/64d0857967ad44e06276830d67d885570ec44e69/patches/th-lift-0.8.1.patch#L47-51), [`shakespeare`](https://gitlab.haskell.org/ghc/head.hackage/-/blob/64d0857967ad44e06276830d67d885570ec44e69/patches/shakespeare-2.0.24.1.patch#L27-31), [`aeson`](https://gitlab.haskell.org/ghc/head.hackage/-/blob/64d0857967ad44e06276830d67d885570ec44e69/patches/aeson-1.5.3.0.patch#L10-14), and [`th-orphans`](https://gitlab.haskell.org/ghc/head.hackage/-/blob/64d0857967ad44e06276830d67d885570ec44e69/patches/th-orphans-0.13.10.patch#L10-17). In other words, any library that manually implements `liftTyped` by coercing through `lift` will need to use something like the function above.

**Comment by phadej** [comment]
@RyanGlScott that's `liftGHCSplice` (the alias we don't yet have, but might)?

I.e. I'd name the function as `liftWhateverAliasWeWouldUse`.

**Comment by RyanGlScott** [comment]
Right, I faintly remember discussing this in #1. If I understand your proposal correctly, you would choose the `-Splice` suffix to denote things that have their types differ conditionally between `Code` and `TExp`? If so, would you be happy with `liftTypedFromUntypedSplice :: (Lift t, Quote m) => t -> Splice m t` (where `Splice` is defined [here](https://github.com/haskell-compat/th-compat/pull/1#discussion_r463577396))?

**Comment by phadej** [comment]
`liftTypedFromUntypedSplice` is a good name. We should have a clear docs that it's never a `liftTyped` / `liftCode` directly. To differentiate it from possible `liftSplice`.

**Comment by RyanGlScott** [comment]
See #5.

**Comment by RyanGlScott** [comment]
I've uploaded [`th-compat-0.1`](http://hackage.haskell.org/package/th-compat-0.1) to Hackage.

**Comment by phadej** [comment]
:fireworks:
